### ISSUE TITLE
Support for days beyond March 306

### ISSUE THREAD

**Issue by 9len** [mdayaram/calendar2020#1]
Eg, what we would have called January 1st, 2021 would now be called "March 307, 2020"

**Comment by mdayaram** [comment]
Supposedly, that's when calendar2021 would start, but the covid-19 calendar was not quite clear on that, so we'll will have to wait and see.

**Comment by mdayaram** [comment]
Fixed by https://github.com/mdayaram/calendar2020/pull/2
